# Generated by Django 5.2.6 on 2025-09-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='last_modified',
        ),
    ]
