# Generated by Django 5.2.6 on 2025-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_remove_geeksmodel_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
